name: inspection-app-pre-staging
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    # Using basic-s (2GB RAM) for reliable Next.js builds
    # After successful build, you can scale down to basic-xxs if needed
    instance_size_slug: basic-s
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${NEXT_PUBLIC_SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ${SUPABASE_SERVICE_ROLE_KEY}
        type: SECRET
