# DigitalOcean App Platform Specification
# Production deployment configuration for PWA Inspection Platform
# This file defines how your app should be built and deployed on DigitalOcean

name: pwa-inspection-platform
region: sgp

# Services - defines the components of your application
services:
  # Main Next.js web application
  - name: web
    # Source code configuration - Production branch
    github:
      repo: aimiaziah/hse-platform
      branch: main
      deploy_on_push: true

    # Production build configuration
    build_command: npm ci && npm run build

    # Production run configuration
    run_command: npm start

    # Environment configuration
    environment_slug: node-js
    instance_count: 1
    # Production instance sizing:
    # basic-xxs: $5/month (512MB RAM, 1 vCPU) - suitable for small production apps
    # basic-xs: $12/month (1GB RAM, 1 vCPU) - recommended for production with moderate traffic
    # basic-s: $24/month (2GB RAM, 1 vCPU) - recommended for production with higher traffic
    instance_size_slug: basic-xxs

    # HTTP configuration
    http_port: 8080

    # Production health check configuration
    health_check:
      http_path: /api/health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables for web service
    envs:
      # Node.js configuration - Use Node 20 LTS
      - key: NODE_VERSION
        value: '20'
        scope: BUILD_TIME

      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME

      # Next.js configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
        scope: RUN_AND_BUILD_TIME

      # Supabase configuration (set these in App Platform UI)
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET

      # Authentication configuration
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: JWT_EXPIRES_IN
        value: '7d'
        scope: RUN_TIME

      - key: ALLOWED_EMAIL_DOMAINS
        value: 'theta-edge.com'
        scope: RUN_TIME

      # Feature flags
      - key: ENABLE_PIN_AUTH
        value: 'true'
        scope: RUN_TIME

      - key: ENABLE_MICROSOFT_AUTH
        value: 'true'
        scope: RUN_TIME

      - key: PREFER_MICROSOFT_AUTH
        value: 'true'
        scope: RUN_TIME

      # Rate limiting configuration
      - key: AUTH_RATE_LIMIT_MAX_REQUESTS
        value: '5'
        scope: RUN_TIME

      - key: AUTH_RATE_LIMIT_WINDOW_MS
        value: '900000'
        scope: RUN_TIME

      # DigitalOcean Spaces configuration (optional - for image storage)
      - key: DO_SPACES_NAME
        value: 'inspection-images'
        scope: RUN_TIME

      - key: DO_SPACES_REGION
        value: 'sgp1'
        scope: RUN_TIME

      - key: DO_SPACES_ENDPOINT
        value: 'https://sgp1.digitaloceanspaces.com'
        scope: RUN_TIME

      - key: DO_SPACES_KEY
        scope: RUN_TIME
        type: SECRET

      - key: DO_SPACES_SECRET
        scope: RUN_TIME
        type: SECRET

      # SharePoint OAuth (optional)
      - key: NEXT_PUBLIC_SHAREPOINT_OAUTH_CLIENT_ID
        scope: RUN_TIME
        type: SECRET

      - key: NEXT_PUBLIC_SHAREPOINT_TENANT_ID
        value: 'common'
        scope: RUN_TIME

      - key: NEXT_PUBLIC_SHAREPOINT_SITE_URL
        value: 'https://thetaedgebhd.sharepoint.com/sites/ThetaEdge'
        scope: RUN_TIME

      - key: NEXT_PUBLIC_SHAREPOINT_LIBRARY_NAME
        value: 'Shared Documents'
        scope: RUN_TIME

      - key: NEXT_PUBLIC_SHAREPOINT_BASE_FOLDER
        value: 'HSE'
        scope: RUN_TIME

      # Production logging configuration
      - key: LOG_LEVEL
        value: 'info'
        scope: RUN_TIME

      # Production optimizations
      - key: NEXT_PUBLIC_APP_ENV
        value: 'production'
        scope: RUN_AND_BUILD_TIME

      # Application settings
      - key: NEXT_PUBLIC_APP_NAME
        value: 'PWA Inspection Platform'
        scope: RUN_AND_BUILD_TIME

      - key: NEXT_PUBLIC_APP_VERSION
        value: '1.0.0'
        scope: RUN_AND_BUILD_TIME

      # AI Model Server Configuration
      - key: AI_DEPLOYMENT_TYPE
        value: 'digitalocean'
        scope: RUN_TIME

      - key: AI_MODEL_ENDPOINT
        value: 'http://ai-model-server:8080'
        scope: RUN_TIME

      - key: AI_MIN_CONFIDENCE
        value: '0.5'
        scope: RUN_TIME

      - key: AI_TIMEOUT_MS
        value: '30000'
        scope: RUN_TIME

  # YOLO AI Model Server (Python FastAPI)
  - name: ai-model-server
    # Source code configuration - same repo
    github:
      repo: aimiaziah/hse-platform
      branch: main
      deploy_on_push: true

    # Python build configuration
    build_command: pip install -r requirements.txt

    # Run FastAPI server
    run_command: python model_server.py --host 0.0.0.0 --port 8080

    # Environment configuration
    environment_slug: python
    instance_count: 1
    # AI model server needs more resources for ML inference
    # basic-xs: $12/month (1GB RAM) - minimum for YOLO with ONNX
    # basic-s: $24/month (2GB RAM) - recommended for PyTorch model
    instance_size_slug: basic-xs

    # HTTP configuration
    http_port: 8080
    # Make this service internal only (not publicly accessible)
    # The Next.js app will communicate with it internally
    internal_ports:
      - 8080

    # Health check for model server
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables (configure these in DigitalOcean dashboard)
    envs:
      # Node.js configuration
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME

      - key: NODE_VERSION
        value: '18'
        scope: BUILD_TIME

      # Next.js configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
        scope: RUN_AND_BUILD_TIME

      # Supabase configuration (set these in App Platform UI)
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET

      # Authentication configuration
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: JWT_EXPIRES_IN
        value: '7d'
        scope: RUN_TIME

      - key: ALLOWED_EMAIL_DOMAINS
        value: 'theta-edge.com'
        scope: RUN_TIME

      # Feature flags
      - key: ENABLE_PIN_AUTH
        value: 'true'
        scope: RUN_TIME

      - key: ENABLE_MICROSOFT_AUTH
        value: 'true'
        scope: RUN_TIME

      - key: PREFER_MICROSOFT_AUTH
        value: 'true'
        scope: RUN_TIME

      # Rate limiting configuration
      - key: AUTH_RATE_LIMIT_MAX_REQUESTS
        value: '5'
        scope: RUN_TIME

      - key: AUTH_RATE_LIMIT_WINDOW_MS
        value: '900000'
        scope: RUN_TIME

      # DigitalOcean Spaces configuration (optional - for image storage)
      - key: DO_SPACES_NAME
        value: 'inspection-images'
        scope: RUN_TIME

      - key: DO_SPACES_REGION
        value: 'sgp1'
        scope: RUN_TIME

      - key: DO_SPACES_ENDPOINT
        value: 'https://sgp1.digitaloceanspaces.com'
        scope: RUN_TIME

      - key: DO_SPACES_KEY
        scope: RUN_TIME
        type: SECRET

      - key: DO_SPACES_SECRET
        scope: RUN_TIME
        type: SECRET

      # SharePoint OAuth (optional)
      - key: NEXT_PUBLIC_SHAREPOINT_OAUTH_CLIENT_ID
        scope: RUN_TIME
        type: SECRET

      - key: NEXT_PUBLIC_SHAREPOINT_TENANT_ID
        value: 'common'
        scope: RUN_TIME

      - key: NEXT_PUBLIC_SHAREPOINT_SITE_URL
        value: 'https://thetaedgebhd.sharepoint.com/sites/ThetaEdge'
        scope: RUN_TIME

      - key: NEXT_PUBLIC_SHAREPOINT_LIBRARY_NAME
        value: 'Shared Documents'
        scope: RUN_TIME

      - key: NEXT_PUBLIC_SHAREPOINT_BASE_FOLDER
        value: 'HSE'
        scope: RUN_TIME

      # Production logging configuration
      - key: LOG_LEVEL
        value: 'info'
        scope: RUN_TIME

      # Production optimizations
      - key: NEXT_PUBLIC_APP_ENV
        value: 'production'
        scope: RUN_AND_BUILD_TIME

      # Application settings
      - key: NEXT_PUBLIC_APP_NAME
        value: 'PWA Inspection Platform'
        scope: RUN_AND_BUILD_TIME

      - key: NEXT_PUBLIC_APP_VERSION
        value: '1.0.0'
        scope: RUN_AND_BUILD_TIME

      # Optional: App URL (for OAuth redirects - set after deployment)
      # - key: NEXT_PUBLIC_APP_URL
      #   value: 'https://your-app-name.ondigitalocean.app'
      #   scope: RUN_AND_BUILD_TIME

      # AI Model Server Configuration
      - key: AI_DEPLOYMENT_TYPE
        value: 'digitalocean'
        scope: RUN_TIME

      - key: AI_MODEL_ENDPOINT
        value: 'http://ai-model-server:8080'
        scope: RUN_TIME

      - key: AI_MIN_CONFIDENCE
        value: '0.5'
        scope: RUN_TIME

      - key: AI_TIMEOUT_MS
        value: '30000'
        scope: RUN_TIME

# Production alerts configuration
# These alerts will notify you of important deployment events
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DEPLOYMENT_LIVE
  - rule: DOMAIN_FAILED
  - rule: DOMAIN_LIVE
