// src/utils/inspectionPdfGenerator.ts
// Comprehensive PDF generation for all inspection types

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { generateFirstAidPDF } from './templatePdfGenerator';

interface InspectionData {
  id: string;
  inspection_number: string;
  inspection_type: 'fire_extinguisher' | 'first_aid' | 'hse_general' | string;
  inspector_id: string;
  inspected_by: string;
  designation?: string | null;
  inspection_date: string;
  submitted_at?: string | null;
  reviewed_at?: string | null;
  status: 'draft' | 'pending_review' | 'approved' | 'rejected' | 'completed';
  reviewer_id?: string | null;
  review_comments?: string | null;
  form_data: Record<string, unknown>;
  signature?: string | null;
  remarks?: string | null;
}

interface SupervisorOverviewData {
  inspections: InspectionData[];
  supervisorName: string;
  generatedDate: string;
  filterCriteria?: {
    startDate?: string;
    endDate?: string;
    inspectionType?: string;
    status?: string;
  };
}

/**
 * Format date string
 */
function formatDate(dateString: string): string {
  try {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return dateString;
  }
}

/**
 * Get human-readable inspection type name
 */
function getInspectionTypeName(type: string): string {
  switch (type) {
    case 'fire_extinguisher':
      return 'Fire Extinguisher Inspection';
    case 'first_aid':
      return 'First Aid Kit Inspection';
    case 'hse_general':
      return 'HSE General Inspection';
    default:
      return type;
  }
}

/**
 * Format status for display
 */
function formatStatus(status: string): string {
  return status.toUpperCase().replace('_', ' ');
}

/**
 * Add footer to PDF
 */
function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128);
    doc.text(
      `Generated by PWA Inspection Platform - ${new Date().toLocaleString()}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' },
    );
  }
}

/**
 * Calculate statistics from inspections
 */
function calculateStatistics(inspections: InspectionData[]) {
  return {
    total: inspections.length,
    pending: inspections.filter((i) => i.status === 'pending_review').length,
    approved: inspections.filter((i) => i.status === 'approved').length,
    rejected: inspections.filter((i) => i.status === 'rejected').length,
    fireExtinguisher: inspections.filter((i) => i.inspection_type === 'fire_extinguisher').length,
    firstAid: inspections.filter((i) => i.inspection_type === 'first_aid').length,
    hseGeneral: inspections.filter((i) => i.inspection_type === 'hse_general').length,
  };
}

/**
 * Add fire extinguisher inspection details
 */
function addFireExtinguisherDetails(
  doc: jsPDF,
  formData: Record<string, unknown>,
  startYPosition: number,
): number {
  let currentYPosition = startYPosition;
  if (currentYPosition > 200) {
    doc.addPage();
    currentYPosition = 20;
  }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Fire Extinguisher Inspection Details', 14, currentYPosition);
  currentYPosition += 8;

  const extinguishers = (formData.extinguishers as Array<Record<string, unknown>>) || [];

  if (extinguishers.length === 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('No extinguisher data available', 14, currentYPosition);
    return currentYPosition + 10;
  }

  // Create table for extinguishers
  const tableData = extinguishers.map((ext: Record<string, unknown>) => {
    const issues: string[] = [];
    if (ext.shellRusted) issues.push('Shell Rusted');
    if (ext.hosePerished) issues.push('Hose Perished');
    if (ext.nozzleBlocked) issues.push('Nozzle Blocked');
    if (ext.pressureGaugeFaulty) issues.push('Pressure Faulty');
    if (ext.safetyPinMissing) issues.push('Pin Missing');
    if (ext.pinSealBroken) issues.push('Seal Broken');
    if (!ext.accessible) issues.push('Not Accessible');
    if (ext.missingOrNotInPlace) issues.push('Missing/Not in Place');
    if (ext.emptyOrPressureLow) issues.push('Empty/Low Pressure');

    return [
      (ext.serialNumber || ext.assetNumber || 'N/A') as string,
      (ext.location || 'N/A') as string,
      (ext.typeSize || 'N/A') as string,
      (ext.expiryDate || 'N/A') as string,
      issues.length > 0 ? issues.join(', ') : 'OK',
      (ext.remarks || '-') as string,
    ];
  });

  autoTable(doc, {
    startY: currentYPosition,
    head: [['Serial #', 'Location', 'Type/Size', 'Expiry', 'Issues', 'Remarks']],
    body: tableData,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [231, 76, 60], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 30 },
      2: { cellWidth: 25 },
      3: { cellWidth: 25 },
      4: { cellWidth: 45 },
      5: { cellWidth: 30 },
    },
    didDrawPage: () => {
      // Add page numbers on new pages
      const pageInfo = (
        doc as { internal?: { getCurrentPageInfo?: () => { pageNumber: number } } }
      ).internal?.getCurrentPageInfo?.();
      if (pageInfo && pageInfo.pageNumber > 1) {
        const pageWidth = doc.internal.pageSize.getWidth();
        const currentPage = pageInfo.pageNumber;
        doc.setFontSize(8);
        doc.text(`Page ${currentPage}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, {
          align: 'center',
        });
      }
    },
  });

  const lastTable = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable;
  return lastTable ? lastTable.finalY + 10 : currentYPosition + 10;
}

/**
 * Add first aid kit inspection details
 */
function addFirstAidDetails(
  doc: jsPDF,
  formData: Record<string, unknown>,
  startYPosition: number,
): number {
  let currentYPosition = startYPosition;
  if (currentYPosition > 200) {
    doc.addPage();
    currentYPosition = 20;
  }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('First Aid Kit Inspection Details', 14, currentYPosition);
  currentYPosition += 8;

  const kits = (formData.kits as Array<Record<string, unknown>>) || [];

  if (kits.length === 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('No first aid kit data available', 14, currentYPosition);
    return currentYPosition + 10;
  }

  // For each kit, show items
  kits.forEach((kit: Record<string, unknown>, kitIndex: number) => {
    if (currentYPosition > 250) {
      doc.addPage();
      currentYPosition = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(
      `Kit Location: ${(kit.location as string) || `Kit ${kitIndex + 1}`}`,
      14,
      currentYPosition,
    );
    currentYPosition += 6;

    const items = (kit.items as Array<Record<string, unknown>>) || [];
    const tableData = items.map((item: Record<string, unknown>) => [
      (item.itemName || 'N/A') as string,
      (item.quantity?.toString() || '0') as string,
      (item.expiryDate || 'N/A') as string,
      (item.status || 'OK') as string,
    ]);

    autoTable(doc, {
      startY: currentYPosition,
      head: [['Item Name', 'Quantity', 'Expiry Date', 'Status']],
      body: tableData,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [46, 204, 113], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 25 },
        2: { cellWidth: 35 },
        3: { cellWidth: 40 },
      },
    });

    const lastTable = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable;
    currentYPosition = lastTable ? lastTable.finalY + 10 : currentYPosition + 10;
  });

  return currentYPosition;
}

/**
 * Add HSE general inspection details
 */
function addHSEInspectionDetails(
  doc: jsPDF,
  formData: Record<string, unknown>,
  startYPosition: number,
): number {
  let currentYPosition = startYPosition;
  if (currentYPosition > 200) {
    doc.addPage();
    currentYPosition = 20;
  }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('HSE General Inspection Details', 14, currentYPosition);
  currentYPosition += 8;

  // Add contractor info if available
  if (formData.contractorInfo) {
    const info = formData.contractorInfo as Record<string, unknown>;
    const contractorData = [
      ['Contractor:', (info.contractorName || 'N/A') as string],
      ['Location:', (info.location || 'N/A') as string],
      ['Work Activity:', (info.workActivity || 'N/A') as string],
    ];

    autoTable(doc, {
      startY: currentYPosition,
      head: [],
      body: contractorData,
      theme: 'plain',
      styles: { fontSize: 9 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 40 },
        1: { cellWidth: 'auto' },
      },
    });

    const lastTable = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable;
    currentYPosition = lastTable ? lastTable.finalY + 10 : currentYPosition + 10;
  }

  // Add inspection categories
  const categories = (formData.categories as Array<Record<string, unknown>>) || [];

  if (categories.length > 0) {
    categories.forEach((category: Record<string, unknown>) => {
      if (currentYPosition > 250) {
        doc.addPage();
        currentYPosition = 20;
      }

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text((category.name || 'Category') as string, 14, currentYPosition);
      currentYPosition += 6;

      const items = (category.items as Array<Record<string, unknown>>) || [];
      const tableData = items.map((item: Record<string, unknown>) => [
        (item.question || item.label || 'N/A') as string,
        (item.answer || item.rating || 'N/A') as string,
        (item.notes || item.remarks || '-') as string,
      ]);

      if (tableData.length > 0) {
        autoTable(doc, {
          startY: currentYPosition,
          head: [['Item', 'Rating', 'Notes']],
          body: tableData,
          theme: 'grid',
          styles: { fontSize: 8, cellPadding: 2 },
          headStyles: { fillColor: [52, 152, 219], textColor: 255, fontStyle: 'bold' },
          columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 25 },
            2: { cellWidth: 75 },
          },
        });

        const lastTable = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable;
        currentYPosition = lastTable ? lastTable.finalY + 10 : currentYPosition + 10;
      }
    });
  }

  // Add observations if available
  if (
    formData.observations &&
    Array.isArray(formData.observations) &&
    formData.observations.length > 0
  ) {
    if (currentYPosition > 250) {
      doc.addPage();
      currentYPosition = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Observations:', 14, currentYPosition);
    currentYPosition += 6;

    const obsData = (formData.observations as Array<Record<string, unknown>>).map(
      (obs: Record<string, unknown>, idx: number) => [
        (idx + 1).toString(),
        (obs.observation || obs.note || 'N/A') as string,
      ],
    );

    autoTable(doc, {
      startY: currentYPosition,
      head: [['#', 'Observation']],
      body: obsData,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [155, 89, 182], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 'auto' },
      },
    });

    const lastTable = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable;
    currentYPosition = lastTable ? lastTable.finalY + 10 : currentYPosition + 10;
  }

  return currentYPosition;
}

/**
 * Generate a single inspection PDF report
 */
export function generateInspectionPDF(inspection: InspectionData): jsPDF {
  // Use specialized template for first aid inspections
  if (inspection.inspection_type === 'first_aid') {
    return generateFirstAidPDF({
      inspectedBy: inspection.inspected_by,
      designation: inspection.designation || 'HSE',
      inspectionDate: inspection.inspection_date,
      signature: inspection.signature || undefined,
      kits: Array.isArray(inspection.form_data.kits) ? inspection.form_data.kits : [],
    });
  }

  // Default format for other inspection types
  // eslint-disable-next-line new-cap
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let currentYPosition = 20;

  // Add company logo/header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Inspection Report', pageWidth / 2, currentYPosition, { align: 'center' });

  currentYPosition += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(getInspectionTypeName(inspection.inspection_type), pageWidth / 2, currentYPosition, {
    align: 'center',
  });

  currentYPosition += 15;

  // Inspection Details Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Inspection Information', 14, currentYPosition);
  currentYPosition += 8;

  const inspectionInfo = [
    ['Inspection Number:', inspection.inspection_number],
    ['Type:', getInspectionTypeName(inspection.inspection_type)],
    ['Inspector:', inspection.inspected_by],
    ['Designation:', inspection.designation || 'N/A'],
    ['Inspection Date:', formatDate(inspection.inspection_date)],
    [
      'Submitted At:',
      inspection.submitted_at ? formatDate(inspection.submitted_at) : 'Not submitted',
    ],
    ['Status:', inspection.status.toUpperCase().replace('_', ' ')],
  ];

  if (inspection.reviewed_at) {
    inspectionInfo.push(['Reviewed At:', formatDate(inspection.reviewed_at)]);
  }

  if (inspection.review_comments) {
    inspectionInfo.push(['Review Comments:', inspection.review_comments]);
  }

  autoTable(doc, {
    startY: currentYPosition,
    head: [],
    body: inspectionInfo,
    theme: 'plain',
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 45 },
      1: { cellWidth: 'auto' },
    },
  });

  const lastTable = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable;
  currentYPosition = lastTable ? lastTable.finalY + 15 : currentYPosition + 15;

  // Type-specific inspection details
  switch (inspection.inspection_type) {
    case 'fire_extinguisher':
      currentYPosition = addFireExtinguisherDetails(doc, inspection.form_data, currentYPosition);
      break;
    case 'first_aid':
      currentYPosition = addFirstAidDetails(doc, inspection.form_data, currentYPosition);
      break;
    case 'hse_general':
      currentYPosition = addHSEInspectionDetails(doc, inspection.form_data, currentYPosition);
      break;
    default:
      // No additional details for other types
      break;
  }

  // Add signature if available
  if (inspection.signature) {
    if (currentYPosition > 240) {
      doc.addPage();
      currentYPosition = 20;
    }
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Inspector Signature:', 14, currentYPosition);
    currentYPosition += 10;
    try {
      doc.addImage(inspection.signature, 'PNG', 14, currentYPosition, 60, 30);
      currentYPosition += 35;
    } catch (error) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.text('Signature image unavailable', 14, currentYPosition);
      currentYPosition += 10;
    }
  }

  // Add footer
  addFooter(doc);

  return doc;
}

/**
 * Generate supervisor overview PDF with multiple inspections
 */
export function generateSupervisorOverviewPDF(data: SupervisorOverviewData): jsPDF {
  // eslint-disable-next-line new-cap
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let currentYPosition = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Supervisor Review Report', pageWidth / 2, currentYPosition, { align: 'center' });

  currentYPosition += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated for: ${data.supervisorName}`, pageWidth / 2, currentYPosition, {
    align: 'center',
  });

  currentYPosition += 5;
  doc.text(`Generated on: ${formatDate(data.generatedDate)}`, pageWidth / 2, currentYPosition, {
    align: 'center',
  });

  currentYPosition += 15;

  // Filter criteria if provided
  if (data.filterCriteria) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Filter Criteria:', 14, currentYPosition);
    currentYPosition += 6;
    doc.setFont('helvetica', 'normal');

    if (data.filterCriteria.startDate || data.filterCriteria.endDate) {
      const dateRange = `${
        data.filterCriteria.startDate ? formatDate(data.filterCriteria.startDate) : 'Start'
      } - ${data.filterCriteria.endDate ? formatDate(data.filterCriteria.endDate) : 'End'}`;
      doc.text(`Date Range: ${dateRange}`, 14, currentYPosition);
      currentYPosition += 5;
    }

    if (data.filterCriteria.inspectionType) {
      doc.text(
        `Type: ${getInspectionTypeName(data.filterCriteria.inspectionType)}`,
        14,
        currentYPosition,
      );
      currentYPosition += 5;
    }

    if (data.filterCriteria.status) {
      doc.text(
        `Status: ${data.filterCriteria.status.toUpperCase().replace('_', ' ')}`,
        14,
        currentYPosition,
      );
      currentYPosition += 5;
    }

    currentYPosition += 10;
  }

  // Summary statistics
  const stats = calculateStatistics(data.inspections);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary Statistics', 14, currentYPosition);
  currentYPosition += 8;

  const statsData = [
    ['Total Inspections:', stats.total.toString()],
    ['Pending Review:', stats.pending.toString()],
    ['Approved:', stats.approved.toString()],
    ['Rejected:', stats.rejected.toString()],
    ['Fire Extinguisher:', stats.fireExtinguisher.toString()],
    ['First Aid:', stats.firstAid.toString()],
    ['HSE General:', stats.hseGeneral.toString()],
  ];

  autoTable(doc, {
    startY: currentYPosition,
    head: [],
    body: statsData,
    theme: 'plain',
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 'auto' },
    },
  });

  const lastTable1 = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable;
  currentYPosition = lastTable1 ? lastTable1.finalY + 15 : currentYPosition + 15;

  // Inspections table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Inspections List', 14, currentYPosition);
  currentYPosition += 8;

  const tableData = data.inspections.map((inspection) => [
    inspection.inspection_number,
    getInspectionTypeName(inspection.inspection_type),
    inspection.inspected_by,
    formatDate(inspection.inspection_date),
    inspection.submitted_at ? formatDate(inspection.submitted_at) : 'Not submitted',
    formatStatus(inspection.status),
  ]);

  autoTable(doc, {
    startY: currentYPosition,
    head: [['Inspection #', 'Type', 'Inspector', 'Date', 'Submitted', 'Status']],
    body: tableData,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 35 },
      2: { cellWidth: 30 },
      3: { cellWidth: 25 },
      4: { cellWidth: 30 },
      5: { cellWidth: 25 },
    },
    didDrawPage: () => {
      // Add page numbers
      const pageCount = doc.getNumberOfPages();
      const pageInfo = (
        doc as { internal?: { getCurrentPageInfo?: () => { pageNumber: number } } }
      ).internal?.getCurrentPageInfo?.();
      const currentPage = pageInfo ? pageInfo.pageNumber : 1;
      doc.setFontSize(8);
      doc.text(
        `Page ${currentPage} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' },
      );
    },
  });

  // Add footer
  addFooter(doc);

  return doc;
}

/**
 * Download PDF
 */
export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename);
}

/**
 * Convenience function to generate and download single inspection PDF
 */
export function generateAndDownloadInspectionPDF(inspection: InspectionData) {
  const pdf = generateInspectionPDF(inspection);
  const filename = `Inspection_${inspection.inspection_number}_${formatDate(
    inspection.inspection_date,
  )}.pdf`;
  downloadPDF(pdf, filename);
}

/**
 * Convenience function to generate and download supervisor overview PDF
 */
export function generateAndDownloadSupervisorOverviewPDF(data: SupervisorOverviewData) {
  const pdf = generateSupervisorOverviewPDF(data);
  const filename = `Supervisor_Overview_${formatDate(data.generatedDate)}.pdf`;
  downloadPDF(pdf, filename);
}
