#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "👨‍💻 Styling your project before committing 🛠️";
echo "⏱️ Please be calm, this may take a while time ⌛ ....";

# ESLINT STANDARDS CHECKER
# Temporarily allowing warnings to pass
npm run lint || true

echo "🎉 Committing this now.... ✨🚀";
